// src/routes/transactions/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { SubmitFunction } from '@sveltejs/kit';
	import { Plus, Pencil, Trash2, ReceiptText, ArrowDownLeft, ArrowUpRight, ArrowLeftRight } from '@lucide/svelte';
	import TransactionForm from '$lib/components/TransactionForm.svelte';
	import ConfirmModal from '$lib/components/ConfirmModal.svelte';
	import WalletSelect from '$lib/components/WalletSelect.svelte';
	import { notify } from '$lib/stores.svelte';
	import { formatIDR, formatDate } from '$lib/format';
	import { CATEGORIES } from '$lib/constants';
	import type { TxRow } from '$lib/server/db';

	let { data } = $props();

	let showForm = $state(false);
	let editing = $state<TxRow | null>(null);
	let deleteTarget = $state<TxRow | null>(null);
	let deleting = $state(false);
	let deleteForm: HTMLFormElement | null = null;

	const monthIncome = $derived(
		data.transactions.filter((t) => t.type === 'income').reduce((s, t) => s + t.amount, 0)
	);
	const monthExpense = $derived(
		data.transactions.filter((t) => t.type === 'expense').reduce((s, t) => s + t.amount, 0)
	);

	// Opened by the mobile nav Catat FAB via window event (no shared state).
	$effect(() => {
		const open = () => {
			editing = null;
			showForm = true;
		};
		window.addEventListener('open-transaction-form', open);
		return () => window.removeEventListener('open-transaction-form', open);
	});

	function openAdd() {
		editing = null;
		showForm = true;
	}

	function openEdit(tx: TxRow) {
		editing = tx;
		showForm = true;
	}

	const handleDelete: SubmitFunction = () => {
		deleting = true;
		return async ({ result, update }) => {
			deleting = false;
			deleteTarget = null;
			await update();
			if (result.type === 'success') notify('success', 'Transaksi dihapus');
			else notify('error', 'Gagal menghapus transaksi');
		};
	};

	function onMonthChange(e: Event) {
		(e.currentTarget as HTMLFormElement).requestSubmit();
	}

	function filterHref(wallet: string | null, offset = 0) {
		const p = new URLSearchParams();
		if (data.month) p.set('month', data.month);
		if (wallet) p.set('wallet', wallet);
		if (data.q) p.set('q', data.q);
		if (data.category) p.set('category', data.category);
		if (offset > 0) p.set('offset', String(offset));
		const q = p.toString();
		return q ? `/transactions?${q}` : '/transactions';
	}

	function isChipActive(wallet: string | null) {
		return wallet ? data.wallet === wallet : !data.wallet;
	}

	// ?wallet= holds a kind ('digital'|'cash') or a wallet id; select only preselects ids.
	const selectedWalletId = $derived(
		data.wallet && data.wallet !== 'digital' && data.wallet !== 'cash' ? data.wallet : ''
	);

	const monthLabel = $derived(
		data.month
			? new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(
					new Date(data.month + '-01')
				)
			: ''
	);
</script>

<svelte:head>
	<title>Transaksi · Digital Wallet</title>
</svelte:head>

<main class="mx-auto max-w-3xl px-4 pt-6 pb-28 md:pb-6">
	<div class="page-header">
		<h1 class="page-title">Transaksi</h1>
		<button
			onclick={openAdd}
			class="btn btn-primary px-3 py-2"
		>
			<Plus size={16} /> Catat
		</button>
	</div>

	<section class="card mb-3 p-4" aria-label="Total transaksi">
		<div class="section-header">
			<h2 class="section-title">Total{data.month ? ` ${monthLabel}` : ''}</h2>
		</div>
		<p class="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm">
			<span class="num font-bold tabular-nums text-ctp-green">+ {formatIDR(monthIncome)}</span>
			<span class="num font-bold tabular-nums text-ctp-red">− {formatIDR(monthExpense)}</span>
			<span
				class="num ml-auto font-bold tabular-nums
				{monthIncome - monthExpense < 0 ? 'text-ctp-red' : 'text-ctp-text'}"
			>
				{monthIncome - monthExpense < 0 ? '−' : '+'} {formatIDR(Math.abs(monthIncome - monthExpense))}
			</span>
		</p>
	</section>

	<div class="mb-3 flex flex-wrap gap-1.5" role="group" aria-label="Filter jenis dompet">
		<a
			href={filterHref(null)}
			aria-current={isChipActive(null) ? 'true' : undefined}
			class="{isChipActive(null) ? 'chip-active' : 'chip'} px-3 py-1"
		>
			Semua
		</a>
		<a
			href={filterHref('digital')}
			aria-current={isChipActive('digital') ? 'true' : undefined}
			class="{isChipActive('digital') ? 'chip-active' : 'chip'} px-3 py-1"
		>
			Digital
		</a>
		<a
			href={filterHref('cash')}
			aria-current={isChipActive('cash') ? 'true' : undefined}
			class="{isChipActive('cash') ? 'chip-active' : 'chip'} px-3 py-1"
		>
			Tunai
		</a>
	</div>

	<form method="GET" action="/transactions" class="mb-4 grid grid-cols-2 gap-2 sm:flex sm:flex-wrap sm:items-center">
		<label for="month" class="text-sm text-ctp-subtext1">Bulan</label>
		<input
			id="month"
			name="month"
			type="month"
			value={data.month ?? ''}
			onchange={onMonthChange}
			class="input w-full sm:w-auto"
		/>
		<label for="wallet-filter" class="text-sm text-ctp-subtext1">Dompet</label>
		<WalletSelect
			id="wallet-filter"
			name="wallet"
			value={selectedWalletId}
			placeholder="Semua dompet"
			placeholderDisabled={false}
			className="w-full sm:w-auto"
			wallets={data.wallets}
		/>
		<input
			type="search"
			name="q"
			placeholder="Cari deskripsi…"
			value={data.q}
			aria-label="Cari deskripsi"
			class="input w-full sm:w-auto"
		/>
		<select
			name="category"
			aria-label="Kategori"
			value={data.category}
			class="input w-full sm:w-auto"
		>
			<option value="">Semua kategori</option>
			{#each CATEGORIES as c (c)}
				<option value={c}>{c}</option>
			{/each}
		</select>
		<button
			type="submit"
			class="btn btn-outline col-span-2 px-3 py-2 sm:col-span-1 sm:py-1.5"
		>
			Terapkan
		</button>
		{#if data.month || data.wallet || data.q || data.category}
			<a href="/transactions" class="col-span-2 text-sm text-ctp-peach hover:underline sm:col-span-1">
				Reset
			</a>
		{/if}
	</form>

	{#if data.transactions.length === 0}
		<div class="card py-12 text-center">
			<div
				class="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-ctp-surface0 text-ctp-subtext0"
				aria-hidden="true"
			>
				<ReceiptText size={22} />
			</div>
			<p class="text-sm font-medium text-ctp-text">
				Belum ada transaksi{data.month ? ` untuk ${monthLabel}` : ''}
			</p>
			<p class="mt-1 text-xs text-ctp-subtext0">
				Catat transaksi pertama dengan tombol "Catat" di atas.
			</p>
		</div>
	{:else}
		<ul class="list">
			{#each data.transactions as tx (tx.id)}
				<li class="list-row min-w-0">
					<span
						class="tile h-8 w-8
						{tx.type === 'income'
							? 'bg-ctp-green/15 text-ctp-green'
							: tx.type === 'expense'
								? 'bg-ctp-red/15 text-ctp-red'
								: 'bg-ctp-blue/15 text-ctp-blue'}"
						aria-hidden="true"
					>
						{#if tx.type === 'income'}
							<ArrowDownLeft size={16} />
						{:else if tx.type === 'expense'}
							<ArrowUpRight size={16} />
						{:else}
							<ArrowLeftRight size={16} />
						{/if}
					</span>
					<div class="min-w-0 flex-1">
						<p class="truncate text-sm font-medium text-ctp-text">{tx.description}</p>
					<p class="text-xs text-ctp-subtext0">
						{tx.category} · {formatDate(tx.date)}
					</p>
				</div>
				{#if tx.type === 'transfer' && tx.dest_wallet_name}
					<span class="chip max-sm:sr-only">
						→ {tx.dest_wallet_name}
					</span>
				{/if}
				<span class="chip max-sm:sr-only">
					{tx.wallet_name}
				</span>
					<span
						class="num text-[13px] font-semibold whitespace-nowrap tabular-nums sm:text-sm
						{tx.type === 'transfer'
							? 'text-ctp-blue'
							: tx.type === 'income'
								? 'text-ctp-green'
								: 'text-ctp-red'}"
					>
						{tx.type === 'income' ? '+' : '−'} {formatIDR(tx.amount)}
					</span>
					<div class="flex shrink-0 gap-0.5 sm:gap-1">
						<button
							onclick={() => openEdit(tx)}
							aria-label="Edit {tx.description}"
							class="btn btn-ghost min-h-[40px] min-w-[40px] rounded-lg p-2 sm:min-h-0 sm:min-w-0 sm:p-1.5"
						>
							<Pencil size={15} />
						</button>
						<button
							onclick={() => (deleteTarget = tx)}
							aria-label="Hapus {tx.description}"
							class="btn btn-ghost min-h-[40px] min-w-[40px] rounded-lg p-2 hover:text-ctp-red sm:min-h-0 sm:min-w-0 sm:p-1.5"
						>
							<Trash2 size={15} />
						</button>
					</div>
				</li>
			{/each}
		</ul>
		{#if data.hasMore}
			<div class="mt-3 text-center">
				<a
					href={filterHref(data.wallet ?? null, data.offset + 50)}
					class="btn btn-outline px-4 py-2"
				>
					Muat lebih
				</a>
			</div>
		{/if}
	{/if}
</main>

<TransactionForm transaction={editing} wallets={data.wallets} open={showForm} onclose={() => (showForm = false)} />

<ConfirmModal
	open={!!deleteTarget}
	title="Hapus Transaksi"
	message={deleteTarget
		? `Hapus "${deleteTarget.description}" (${formatIDR(deleteTarget.amount)})? Tindakan ini tidak bisa dibatalkan.`
		: ''}
	confirmText={deleting ? 'Menghapus…' : 'Hapus'}
	onConfirm={() => deleteForm?.requestSubmit()}
	onCancel={() => (deleteTarget = null)}
/>

<form method="POST" action="?/delete" bind:this={deleteForm} use:enhance={handleDelete} class="hidden">
	<input type="hidden" name="id" value={deleteTarget?.id ?? ''} />
</form>

// web/src/pages/Transactions.tsx
import React, { useState, useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
	Plus,
	Pencil,
	Trash2,
	ReceiptText,
	ArrowDownLeft,
	ArrowUpRight,
	ArrowLeftRight
} from 'lucide-react';
import TransactionForm from '../components/TransactionForm';
import ConfirmModal from '../components/ConfirmModal';
import WalletSelect from '../components/WalletSelect';
import Skeleton from '../components/Skeleton';
import { useToast } from '../hooks/useToast';
import { formatIDR, formatDate } from '@shared/format';
import { CATEGORIES } from '@shared/constants';
import { queryKeys } from '../lib/queryKeys';
import { get, del, post } from '../api/client';
import type { TxRow, WalletWithBalance } from '@shared/types';

interface TxResponse {
	transactions: TxRow[];
	hasMore: boolean;
	offset: number;
	limit: number;
}

export default function Transactions() {
	const [searchParams, setSearchParams] = useSearchParams();
	const queryClient = useQueryClient();
	const { notify } = useToast();

	const month = searchParams.get('month') || '';
	const wallet = searchParams.get('wallet') || '';
	const q = searchParams.get('q') || '';
	const category = searchParams.get('category') || '';

	// Local state for filter inputs before submit
	const [inputQ, setInputQ] = useState(q);

	// Modals & action targets
	const [showForm, setShowForm] = useState(false);
	const [editingTx, setEditingTx] = useState<TxRow | null>(null);
	const [deleteTarget, setDeleteTarget] = useState<TxRow | null>(null);

	// Bulk delete selection
	const [selected, setSelected] = useState<Set<string>>(new Set());
	const [showBulkConfirm, setShowBulkConfirm] = useState(false);
	const selectAllRef = useRef<HTMLInputElement>(null);

	// Paging
	const [loadedTx, setLoadedTx] = useState<TxRow[]>([]);
	const [offset, setOffset] = useState(0);

	// Fetch Wallets for dropdown
	const { data: walletsData } = useQuery<{ wallets: WalletWithBalance[] }>({
		queryKey: queryKeys.wallets(),
		queryFn: () => get<{ wallets: WalletWithBalance[] }>('/api/wallets')
	});

	const wallets = walletsData?.wallets ?? [];

	// Build API URL
	const queryUrl = (() => {
		const p = new URLSearchParams();
		if (month) p.set('month', month);
		if (wallet) p.set('walletId', wallet);
		if (q) p.set('search', q);
		if (category) p.set('category', category);
		p.set('limit', '50');
		p.set('offset', String(offset));
		return `/api/transactions?${p.toString()}`;
	})();

	const { data, isLoading } = useQuery<TxResponse>({
		queryKey: queryKeys.transactions({ month, wallet, q, category, offset }),
		queryFn: () => get<TxResponse>(queryUrl)
	});

	// Reset accumulated transactions when filters change
	useEffect(() => {
		setOffset(0);
		setLoadedTx([]);
		setSelected(new Set());
	}, [month, wallet, q, category]);

	// Append transactions on pagination
	useEffect(() => {
		if (data?.transactions) {
			if (offset === 0) {
				setLoadedTx(data.transactions);
			} else {
				setLoadedTx((prev) => {
					const existingIds = new Set(prev.map((t) => t.id));
					const next = data.transactions.filter((t) => !existingIds.has(t.id));
					return [...prev, ...next];
				});
			}
		}
	}, [data, offset]);

	// Mobile nav FAB listener
	useEffect(() => {
		const open = () => {
			setEditingTx(null);
			setShowForm(true);
		};
		window.addEventListener('open-transaction-form', open);
		return () => window.removeEventListener('open-transaction-form', open);
	}, []);

	// Select all checkbox indeterminate state
	const selectedCount = selected.size;
	const allSelected = loadedTx.length > 0 && selectedCount === loadedTx.length;
	const indeterminate = selectedCount > 0 && !allSelected;

	useEffect(() => {
		if (selectAllRef.current) {
			selectAllRef.current.indeterminate = indeterminate;
		}
	}, [indeterminate]);

	const toggleSelectAll = () => {
		if (allSelected) {
			setSelected(new Set());
		} else {
			setSelected(new Set(loadedTx.map((t) => t.id)));
		}
	};

	const toggleRow = (id: string) => {
		const next = new Set(selected);
		if (next.has(id)) next.delete(id);
		else next.add(id);
		setSelected(next);
	};

	// Single Delete Mutation
	const singleDeleteMutation = useMutation({
		mutationFn: (id: string) => del(`/api/transactions/${id}`),
		onSuccess: async () => {
			await Promise.all([
				queryClient.invalidateQueries({ queryKey: ['transactions'] }),
				queryClient.invalidateQueries({ queryKey: ['wallets'] }),
				queryClient.invalidateQueries({ queryKey: ['dashboard'] })
			]);
			setDeleteTarget(null);
			notify('success', 'Transaksi dihapus');
		},
		onError: () => {
			notify('error', 'Gagal menghapus transaksi');
		}
	});

	// Bulk Delete Mutation
	const bulkDeleteMutation = useMutation({
		mutationFn: (ids: string[]) => post<{ deleted: number }>('/api/transactions/bulk-delete', { ids }),
		onSuccess: async (res) => {
			await Promise.all([
				queryClient.invalidateQueries({ queryKey: ['transactions'] }),
				queryClient.invalidateQueries({ queryKey: ['wallets'] }),
				queryClient.invalidateQueries({ queryKey: ['dashboard'] })
			]);
			setSelected(new Set());
			setShowBulkConfirm(false);
			notify('success', `${res.deleted ?? selectedCount} transaksi dihapus`);
		},
		onError: () => {
			notify('error', 'Gagal menghapus transaksi terpilih');
		}
	});

	// Filter helpers
	const updateParam = (key: string, value: string) => {
		const next = new URLSearchParams(searchParams);
		if (value) next.set(key, value);
		else next.delete(key);
		setSearchParams(next);
	};

	const resetFilters = () => {
		setInputQ('');
		setSearchParams(new URLSearchParams());
	};

	// Totals of loaded transactions
	const monthIncome = loadedTx.filter((t) => t.type === 'income').reduce((s, t) => s + t.amount, 0);
	const monthExpense = loadedTx.filter((t) => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
	const monthDiff = monthIncome - monthExpense;

	const monthLabel = month
		? new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(
				new Date(month + '-01')
			)
		: '';

	return (
		<main className="mx-auto max-w-3xl px-4 pt-6 pb-28 md:pb-6">
			{/* Page Header */}
			<div className="page-header">
				<h1 className="page-title">Transaksi</h1>
				<button
					type="button"
					onClick={() => {
						setEditingTx(null);
						setShowForm(true);
					}}
					className="btn btn-primary px-3 py-2 cursor-pointer"
				>
					<Plus size={16} /> Catat
				</button>
			</div>

			{/* Total Transaksi Card */}
			<section className="card mb-3 p-4" aria-label="Total transaksi">
				<div className="section-header">
					<h2 className="section-title">Total{month ? ` ${monthLabel}` : ''}</h2>
				</div>
				<p className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm">
					<span className="num font-bold tabular-nums text-ctp-green">+ {formatIDR(monthIncome)}</span>
					<span className="num font-bold tabular-nums text-ctp-red">− {formatIDR(monthExpense)}</span>
					<span
						className={`num ml-auto font-bold tabular-nums ${
							monthDiff < 0 ? 'text-ctp-red' : 'text-ctp-text'
						}`}
					>
						{monthDiff < 0 ? '−' : '+'} {formatIDR(Math.abs(monthDiff))}
					</span>
				</p>
			</section>

			{/* Kind Chips Filter */}
			<div className="mb-3 flex flex-wrap gap-1.5" role="group" aria-label="Filter jenis dompet">
				<button
					type="button"
					onClick={() => updateParam('wallet', '')}
					className={`${!wallet ? 'chip-active' : 'chip'} px-3 py-1 cursor-pointer`}
				>
					Semua
				</button>
				<button
					type="button"
					onClick={() => updateParam('wallet', 'digital')}
					className={`${wallet === 'digital' ? 'chip-active' : 'chip'} px-3 py-1 cursor-pointer`}
				>
					Digital
				</button>
				<button
					type="button"
					onClick={() => updateParam('wallet', 'cash')}
					className={`${wallet === 'cash' ? 'chip-active' : 'chip'} px-3 py-1 cursor-pointer`}
				>
					Tunai
				</button>
			</div>

			{/* Filter Controls Form */}
			<form
				onSubmit={(e) => {
					e.preventDefault();
					updateParam('q', inputQ.trim());
				}}
				className="mb-4 grid grid-cols-2 gap-2 sm:flex sm:flex-wrap sm:items-center"
			>
				<label htmlFor="tx-filter-month" className="text-sm text-ctp-subtext1">Bulan</label>
				<input
					id="tx-filter-month"
					name="month"
					type="month"
					value={month}
					onChange={(e) => updateParam('month', e.target.value)}
					className="input w-full sm:w-auto"
				/>

				<label htmlFor="tx-filter-wallet" className="text-sm text-ctp-subtext1">Dompet</label>
				<WalletSelect
					id="tx-filter-wallet"
					value={wallet === 'digital' || wallet === 'cash' ? '' : wallet}
					onChange={(e) => updateParam('wallet', e.target.value)}
					placeholder="Semua dompet"
					placeholderDisabled={false}
					className="w-full sm:w-auto"
					wallets={wallets}
				/>

				<input
					type="search"
					name="q"
					placeholder="Cari deskripsi…"
					value={inputQ}
					onChange={(e) => setInputQ(e.target.value)}
					aria-label="Cari deskripsi"
					className="input w-full sm:w-auto"
				/>

				<select
					name="category"
					aria-label="Kategori"
					value={category}
					onChange={(e) => updateParam('category', e.target.value)}
					className="input w-full sm:w-auto"
				>
					<option value="">Semua kategori</option>
					{CATEGORIES.map((c) => (
						<option key={c} value={c}>
							{c}
						</option>
					))}
				</select>

				<button
					type="submit"
					className="btn btn-outline col-span-2 px-3 py-2 sm:col-span-1 sm:py-1.5"
				>
					Terapkan
				</button>

				{(month || wallet || q || category) && (
					<button
						type="button"
						onClick={resetFilters}
						className="col-span-2 text-sm text-ctp-peach hover:underline sm:col-span-1 text-left"
					>
						Reset
					</button>
				)}
			</form>

			{/* Loading State */}
			{isLoading && offset === 0 ? (
				<Skeleton rows={5} />
			) : loadedTx.length === 0 ? (
				/* Empty State */
				<div className="card py-12 text-center">
					<div
						className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-ctp-surface0 text-ctp-subtext0"
						aria-hidden="true"
					>
						<ReceiptText size={22} />
					</div>
					<p className="text-sm font-medium text-ctp-text">
						Belum ada transaksi{month ? ` untuk ${monthLabel}` : ''}
					</p>
					<p className="mt-1 text-xs text-ctp-subtext0">
						Catat transaksi pertama dengan tombol "Catat" di atas.
					</p>
				</div>
			) : (
				<>
					{/* Bulk select header bar */}
					<div className="mb-2 flex items-center justify-between gap-3">
						<label htmlFor="select-all-tx" className="flex items-center gap-2 text-sm text-ctp-subtext1 cursor-pointer">
							<input
								id="select-all-tx"
								ref={selectAllRef}
								type="checkbox"
								checked={allSelected}
								onChange={toggleSelectAll}
								aria-label="Pilih semua transaksi"
								className="h-4 w-4 rounded border-ctp-surface0 accent-ctp-peach dark:border-ctp-surface1"
							/>
							Pilih semua
						</label>

						{selectedCount > 0 && (
							<div className="flex items-center gap-2">
								<span className="text-xs text-ctp-subtext0 hidden sm:inline">
									Menghapus yang terpilih di halaman ini saja.
								</span>
								<button
									type="button"
									onClick={() => setShowBulkConfirm(true)}
									aria-label={`Hapus ${selectedCount} transaksi terpilih`}
									className="btn btn-danger px-3 py-1.5 text-xs sm:text-sm cursor-pointer"
								>
									<Trash2 size={15} /> Hapus ({selectedCount})
								</button>
							</div>
						)}
					</div>

					{/* Transaction List */}
					<ul className="list">
						{loadedTx.map((tx) => (
							<li key={tx.id} className="list-row min-w-0">
								<input
									type="checkbox"
									checked={selected.has(tx.id)}
									onChange={() => toggleRow(tx.id)}
									aria-label={`Pilih transaksi ${tx.description}`}
									className="h-4 w-4 shrink-0 rounded border-ctp-surface0 accent-ctp-peach dark:border-ctp-surface1 mr-1"
								/>
								<span
									className={`tile h-8 w-8 ${
										tx.type === 'income'
											? 'bg-ctp-green/15 text-ctp-green'
											: tx.type === 'expense'
												? 'bg-ctp-red/15 text-ctp-red'
												: 'bg-ctp-blue/15 text-ctp-blue'
									}`}
									aria-hidden="true"
								>
									{tx.type === 'income' ? (
										<ArrowDownLeft size={16} />
									) : tx.type === 'expense' ? (
										<ArrowUpRight size={16} />
									) : (
										<ArrowLeftRight size={16} />
									)}
								</span>

								<div className="min-w-0 flex-1">
									<p className="truncate text-sm font-medium text-ctp-text">{tx.description}</p>
									<p className="text-xs text-ctp-subtext0">
										{tx.category} · {formatDate(tx.date)}
									</p>
								</div>

								{tx.type === 'transfer' && tx.dest_wallet_name && (
									<span className="chip max-sm:sr-only">
										→ {tx.dest_wallet_name}
									</span>
								)}
								<span className="chip max-sm:sr-only">
									{tx.wallet_name}
								</span>

								<span
									className={`num text-[13px] font-semibold whitespace-nowrap tabular-nums sm:text-sm ${
										tx.type === 'transfer'
											? 'text-ctp-blue'
											: tx.type === 'income'
												? 'text-ctp-green'
												: 'text-ctp-red'
									}`}
								>
									{tx.type === 'income' ? '+' : '−'} {formatIDR(tx.amount)}
								</span>

								<div className="flex shrink-0 gap-0.5 sm:gap-1">
									<button
										type="button"
										onClick={() => {
											setEditingTx(tx);
											setShowForm(true);
										}}
										aria-label={`Edit ${tx.description}`}
										className="btn btn-ghost min-h-[40px] min-w-[40px] rounded-lg p-2 sm:min-h-0 sm:min-w-0 sm:p-1.5 cursor-pointer"
									>
										<Pencil size={15} />
									</button>
									<button
										type="button"
										onClick={() => setDeleteTarget(tx)}
										aria-label={`Hapus ${tx.description}`}
										className="btn btn-ghost min-h-[40px] min-w-[40px] rounded-lg p-2 hover:text-ctp-red sm:min-h-0 sm:min-w-0 sm:p-1.5 cursor-pointer"
									>
										<Trash2 size={15} />
									</button>
								</div>
							</li>
						))}
					</ul>

					{/* Load More Button */}
					{data?.hasMore && (
						<div className="mt-3 text-center">
							<button
								type="button"
								onClick={() => setOffset((prev) => prev + 50)}
								className="btn btn-outline px-4 py-2 cursor-pointer"
							>
								Muat lebih
							</button>
						</div>
					)}
				</>
			)}

			{/* Create/Edit Modal */}
			<TransactionForm
				open={showForm}
				transaction={editingTx}
				wallets={wallets}
				onClose={() => {
					setShowForm(false);
					setEditingTx(null);
				}}
			/>

			{/* Single Delete Confirm */}
			<ConfirmModal
				open={!!deleteTarget}
				title="Hapus Transaksi"
				message={
					deleteTarget
						? `Hapus "${deleteTarget.description}" (${formatIDR(deleteTarget.amount)})? Tindakan ini tidak bisa dibatalkan.`
						: ''
				}
				confirmText={singleDeleteMutation.isPending ? 'Menghapus…' : 'Hapus'}
				onConfirm={() => {
					if (deleteTarget) singleDeleteMutation.mutate(deleteTarget.id);
				}}
				onCancel={() => setDeleteTarget(null)}
			/>

			{/* Bulk Delete Confirm */}
			<ConfirmModal
				open={showBulkConfirm}
				title="Hapus Transaksi Terpilih"
				message={`Hapus ${selectedCount} transaksi terpilih? Tindakan ini tidak bisa dibatalkan.`}
				confirmText={bulkDeleteMutation.isPending ? 'Menghapus…' : 'Hapus'}
				onConfirm={() => {
					bulkDeleteMutation.mutate([...selected]);
				}}
				onCancel={() => setShowBulkConfirm(false)}
			/>
		</main>
	);
}
