// src/lib/components/ThemeToggle.svelte
<script lang="ts">
	import { Moon, Sun } from '@lucide/svelte';

	let dark = $state(false);

	function syncThemeColor(isDark: boolean) {
		const meta = document.querySelector('meta[name="theme-color"]');
		if (meta) meta.setAttribute('content', isDark ? '#11111b' : '#eff1f5');
	}

	$effect(() => {
		// Script in app.html already applied the class before paint; just read it.
		dark = document.documentElement.classList.contains('dark');
		syncThemeColor(dark);
	});

	function toggle() {
		dark = !dark;
		document.documentElement.classList.toggle('dark', dark);
		syncThemeColor(dark);
		try {
			localStorage.setItem('ft-theme', dark ? 'dark' : 'light');
		} catch {
			// Private browsing may block storage; theme still applies for this visit
		}
	}
</script>

<button
	type="button"
	onclick={toggle}
	class="btn btn-ghost p-2"
	aria-label={dark ? 'Ganti ke tema terang' : 'Ganti ke tema gelap'}
	aria-pressed={dark}
	title={dark ? 'Ganti ke tema terang' : 'Ganti ke tema gelap'}
>
	{#if dark}
		<Moon size={18} />
	{:else}
		<Sun size={18} />
	{/if}
</button>

// web/src/components/ThemeToggle.tsx
import React, { useState, useEffect } from 'react';
import { Sun, Moon } from 'lucide-react';

function syncThemeColor(isDark: boolean) {
	const meta = document.querySelector('meta[name="theme-color"]');
	if (meta) meta.setAttribute('content', isDark ? '#11111b' : '#eff1f5');
}

export default function ThemeToggle() {
	const [dark, setDark] = useState(false);

	useEffect(() => {
		const isDark = document.documentElement.classList.contains('dark');
		setDark(isDark);
		syncThemeColor(isDark);
	}, []);

	const toggle = () => {
		const next = !dark;
		setDark(next);
		document.documentElement.classList.toggle('dark', next);
		syncThemeColor(next);
		try {
			localStorage.setItem('ft-theme', next ? 'dark' : 'light');
		} catch {
			// Private browsing may block localStorage
		}
	};

	return (
		<button
			type="button"
			onClick={toggle}
			className="btn btn-ghost p-2"
			aria-label={dark ? 'Ganti ke tema terang' : 'Ganti ke tema gelap'}
			aria-pressed={dark}
			title={dark ? 'Ganti ke tema terang' : 'Ganti ke tema gelap'}
		>
			{dark ? <Moon size={18} /> : <Sun size={18} />}
		</button>
	);
}
